name: deploy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build-and-push:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image (multi-platform)
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          PLATFORMS="linux/amd64,linux/arm64"
          TAGS="ghcr.io/${{ github.repository }}:$SHORT_SHA"
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            TAGS+=" --tag ghcr.io/${{ github.repository }}:latest"
          fi
          docker buildx build --platform $PLATFORMS --push -t ghcr.io/${{ github.repository }}:$SHORT_SHA $(if [ "${{ github.ref }}" = "refs/heads/main" ]; then echo "-t ghcr.io/${{ github.repository }}:latest"; fi) .
