name: Build and Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          docker build -t ghcr.io/${{ github.repository }}:$SHORT_SHA .
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            docker tag ghcr.io/${{ github.repository }}:$SHORT_SHA ghcr.io/${{ github.repository }}:latest
          fi

      - name: Push Docker image
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          docker push ghcr.io/${{ github.repository }}:$SHORT_SHA
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            docker push ghcr.io/${{ github.repository }}:latest
          fi
